prevent crash when creditor_identifier is missing
if no creditor_identifier was found the array rejects empty values and
returns nil after which a nil.text is being executed which leads to a an
exception
```
NoMethodError - undefined method 'text' for nil:
```